Add VCS simulation timeout handling

diff --git a/tb/sim/Makefile b/tb/sim/Makefile
--- a/tb/sim/Makefile
+++ b/tb/sim/Makefile
@@ -5,6 +5,7 @@ seed      ?= 1
 verbosity ?= UVM_MEDIUM
 waves     ?= 1
 vseq      ?= reset_vseq,link_up_vseq
+sim_timeout ?= 200000
 
 VCS       ?= /home/synopsys/vcs-mx/O-2018.09-1/bin/vcs
 VERDI     ?= /home/synopsys/verdi/Verdi_O-2018.09-SP2/bin/verdi
@@ -51,6 +52,7 @@ RUN_OPTS += +ntb_random_seed=$(seed)
 RUN_OPTS += +VSEQ=$(vseq)
 RUN_OPTS += +WAVES=$(waves)
 RUN_OPTS += +FSDB_FILE=$(FSDB)
+RUN_OPTS += +SIM_TIMEOUT_NS=$(sim_timeout)
 RUN_OPTS += -cm line+cond+tgl+fsm+branch
 RUN_OPTS += -cm_dir $(COV_DIR)/$(tc)_$(seed).vdb
 
@@ -69,7 +71,7 @@ help:
 	@echo "  make clean                       Remove sim output"
 	@echo ""
 	@echo "Variables:"
-	@echo "  tc=$(tc) seed=$(seed) waves=$(waves) verbosity=$(verbosity)"
+	@echo "  tc=$(tc) seed=$(seed) waves=$(waves) verbosity=$(verbosity) sim_timeout=$(sim_timeout)"
 	@echo "  vseq=$(vseq)"
 
 dirs:
@@ -82,6 +84,10 @@ com comp: dirs
 
 run: com
 	$(SIMV) $(RUN_OPTS) -l $(RUN_LOG)
+	@if grep -Eq 'UVM_(ERROR|FATAL)[[:space:]]*:[[:space:]]*[1-9]' $(RUN_LOG); then \
+	  echo "UVM errors or fatals found in $(RUN_LOG)"; \
+	  exit 1; \
+	fi
 	@echo "tc=$(tc) seed=$(seed) vseq=$(vseq) fsdb=$(FSDB)" > $(META_DIR)/run_$(tc)_$(seed).meta
 
 verdi:
@@ -102,8 +108,13 @@ regress: com
 	  $(SIMV) +UVM_NO_RELNOTES +UVM_TESTNAME=$$test_name +UVM_VERBOSITY=$(verbosity) \
 	    +ntb_random_seed=$$test_seed +VSEQ=$$test_vseq +WAVES=$(waves) \
 	    +FSDB_FILE=$(WAVE_DIR)/$${test_name}_$${test_seed}.fsdb \
+	    +SIM_TIMEOUT_NS=$(sim_timeout) \
 	    -cm line+cond+tgl+fsm+branch -cm_dir $(COV_DIR)/$${test_name}_$${test_seed}.vdb \
 	    -l $(LOG_DIR)/run_$${test_name}_$${test_seed}.log; \
+	  if grep -Eq 'UVM_(ERROR|FATAL)[[:space:]]*:[[:space:]]*[1-9]' $(LOG_DIR)/run_$${test_name}_$${test_seed}.log; then \
+	    echo "UVM errors or fatals found in $(LOG_DIR)/run_$${test_name}_$${test_seed}.log"; \
+	    exit 1; \
+	  fi; \
 	done < $(CASE_LIST)
 	@urg -full64 -dir $(COV_DIR)/*.vdb -dbname $(COV_DIR)/merged.vdb -report $(COV_DIR)/urg_report -log $(LOG_DIR)/urg.log
 
